### ISSUE TITLE
ramMax is not properly parsed from CWL file

### ISSUE THREAD

**Issue by michael-kotliar** [DataBiosphere/toil#3919]
When submitting the following workflow with BSUB on LSF using Toil 5.5.0

```cwl
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
requirements:
  ResourceRequirement:
    ramMax: 3000
    coresMax: 4
stdout: output.txt
inputs:
  message:
    type: string
    inputBinding:
      position: 1
outputs:
  output:
    type: stdout
```

```yaml
message: Hello world!
```

The requested memory is only 3.00 MB, but should be 3 GB

```
TERM_MEMLIMIT: job killed after reaching LSF memory usage limit.
Exited with signal termination: 2.

Resource usage summary:

    CPU time :                                   0.52 sec.
    Max Memory :                                 12 MB
    Average Memory :                             3.00 MB
    Total Requested Memory :                     3.00 MB
    Delta Memory :                               -9.00 MB
    Max Swap :                                   -
    Max Processes :                              4
    Max Threads :                                4
    Run time :                                   0 sec.
    Turnaround time :                            2 sec.

The output (if any) follows:
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1089)
┆friendlyId: TOIL-1089

**Comment by mr-c** [comment]
I think this was fixed in https://github.com/DataBiosphere/toil/commit/50b9f4e8e63c67100274e89116fa17b2109428b9 (from https://github.com/DataBiosphere/toil/pull/3820 )

Can you install from GitHub and test again?

**Comment by adamnovak** [comment]
As mentioned in https://gitter.im/bd2k-genomics-toil/Lobby?at=6194522f10df16294528c288, apparently `ResourceRequirement` on a CWL `CommandLineTool` is not being respected by Toil if the tool is part of a workflow.

**Comment by michael-kotliar** [comment]
@mr-c I checked the latest [commit](https://github.com/DataBiosphere/toil/commit/17a461b1d88c665c2c22da3011c8e65e3b5c0dc8) from Github and this issue is fixed there, however the other one referenced here, is still present
