### ISSUE TITLE
CWL workflows cannot read from S3

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4094]
As noted by @boyangzhao in https://github.com/DataBiosphere/toil/issues/4091#issuecomment-1122732414, `toil-cwl-runner` does not seem to be able to read a CWL `File` object with a `location` set to an S3 URL:

```
txt_file:
  class: File
  location: s3://test/test.cwl
```

We should fix this, and add a test so this can't break again.

This might be a problem for the upcoming AGC release.

**Comment by adamnovak** [comment]
This *should* be under CI here, at least for `File`: https://github.com/DataBiosphere/toil/blob/c4dd55c38d781d151ba5df82530b49cc21981356/src/toil/test/cwl/cwlTest.py#L333-L335

We use [this input](https://github.com/DataBiosphere/toil/blob/a98acdb5cbe0f850b2c11403d147577d9971f4e1/src/toil/test/cwl/download_s3.json) and [this workflow](https://github.com/DataBiosphere/toil/blob/a98acdb5cbe0f850b2c11403d147577d9971f4e1/src/toil/test/cwl/download.cwl) and we check to make sure we get the right standard output from `test -f` on the file.

**Comment by adamnovak** [comment]
This test has not actually been running in CI. We [turned off the jobs that would run the `CWLv10Test` and CWLv11Test` test classes](https://github.com/DataBiosphere/toil/blob/a98acdb5cbe0f850b2c11403d147577d9971f4e1/.gitlab-ci.yml#L184), because we wanted to just run the latest version of the conformance tests, and to make more room for running those in different environments (like against Kubernetes). We didn't notice that the `CWLv10Test` class also contained basic tests like this that we would have still wanted to run.

**Comment by adamnovak** [comment]
I just ran this test manually and it passed.

**Comment by mr-c** [comment]
> I just ran this test manually and it passed.

Maybe it got fixed since the last release?

**Comment by adamnovak** [comment]
OK, I can reproduce this insofar as we can't import `Directory` inputs from S3, which I think might not be under CI.

If you use [this workflow](https://github.com/adamnovak/amazon-genomics-cli/blob/dd7a6f276124c93fb813e4981568f04f2a442f5d/examples/demo-cwl-project/workflows/s3demo/s3demo.cwl) in [this directory](https://github.com/adamnovak/amazon-genomics-cli/tree/dd7a6f276124c93fb813e4981568f04f2a442f5d/examples/demo-cwl-project/workflows/s3demo) with [these inputs](https://github.com/adamnovak/amazon-genomics-cli/blob/dd7a6f276124c93fb813e4981568f04f2a442f5d/examples/demo-cwl-project/workflows/s3demo/inputs.toil.json) (and you have access to the Toil AWS account so you can `GetBucketLocation` on that bucket and get around #4095), then it will fail thusly:

```
(venv) [anovak@courtyard s3demo]$ toil-cwl-runner --jobStore=./tree --clean=always --logDebug ./s3demo.cwl ./inputs.toil.json
[2022-05-11T14:45:05-0700] [MainThread] [D] [toil.statsAndLogging] Suppressing the following loggers: {'requests_oauthlib', 'pyasn1', 'galaxy', 'docker', 'oauthlib', 'charset_normalizer', 'requests', 'prov', 'boto3', 'humanfriendly', 'kubernetes', 'rsa', 'pymesos', 'urllib3', 'dill', 'boto', 'bcdocs', 'google', 'botocore', 'salad', 'cachecontrol', 'websocket', 'rdflib', 'pkg_resources'}
[2022-05-11T14:45:05-0700] [MainThread] [D] [toil.statsAndLogging] Root logger is at level 'DEBUG', 'toil' logger at level 'DEBUG'.
[2022-05-11T14:45:05-0700] [MainThread] [D] [toil.lib.threading] Total machine size: 64 cores
[2022-05-11T14:45:05-0700] [MainThread] [D] [toil.lib.threading] CPU quota: -1
[2022-05-11T14:45:05-0700] [MainThread] [D] [toil.jobStores.fileJobStore] Path to job store directory is '/public/groups/cgl/graph-genomes/anovak/build/amazon-genomics-cli/examples/demo-cwl-project/workflows/s3demo/tree'.
[2022-05-11T14:45:05-0700] [MainThread] [D] [toil.jobStores.abstractJobStore] The workflow ID is: '39e3baf7-6ec4-43ab-a769-afd28ff8394a'
[2022-05-11T14:45:05-0700] [MainThread] [I] [cwltool] Resolved './s3demo.cwl' to 'file:///public/groups/cgl/graph-genomes/anovak/build/amazon-genomics-cli/examples/demo-cwl-project/workflows/s3demo/s3demo.cwl'
[2022-05-11T14:45:18-0700] [MainThread] [D] [toil.cwl.cwltoil] Importing files for ordereddict([('image_file', ordereddict([('class', 'File'), ('location', 's3://toil-datasets/images/toil-logo-draft.png'), ('basename', 'toil-logo-draft.png'), ('nameroot', 'toil-logo-draft'), ('nameext', '.png'), ('streamable', False)])), ('image_directory', ordereddict([('class', 'Directory'), ('location', 's3://toil-datasets/images'), ('basename', 'images')])), ('image_filename', 'toil-logo-draft.png')])
[2022-05-11T14:45:21-0700] [MainThread] [D] [s3transfer.utils] Acquiring 0
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-1_0] [D] [s3transfer.tasks] DownloadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f91e7a4b5e0>}) about to wait for the following futures []
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-1_0] [D] [s3transfer.tasks] DownloadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f91e7a4b5e0>}) done waiting for dependent futures
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-1_0] [D] [s3transfer.tasks] Executing task DownloadSubmissionTask(transfer_id=0, {'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f91e7a4b5e0>}) with kwargs {'client': <botocore.client.S3 object at 0x7f91e7ae28b0>, 'config': <boto3.s3.transfer.TransferConfig object at 0x7f91e7a40670>, 'osutil': <s3transfer.utils.OSUtils object at 0x7f91e7a40df0>, 'request_executor': <s3transfer.futures.BoundedExecutor object at 0x7f91e7a40820>, 'transfer_future': <s3transfer.futures.TransferFuture object at 0x7f91e7a4b5e0>, 'io_executor': <s3transfer.futures.BoundedExecutor object at 0x7f91e7a408e0>}
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-1_0] [D] [s3transfer.futures] Submitting task ImmediatelyWriteIOGetObjectTask(transfer_id=0, {'bucket': 'toil-datasets', 'key': 'images/toil-logo-draft.png', 'extra_args': {}}) to executor <s3transfer.futures.BoundedExecutor object at 0x7f91e7a40820> for transfer request: 0.
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-1_0] [D] [s3transfer.utils] Acquiring 0
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-0_0] [D] [s3transfer.tasks] ImmediatelyWriteIOGetObjectTask(transfer_id=0, {'bucket': 'toil-datasets', 'key': 'images/toil-logo-draft.png', 'extra_args': {}}) about to wait for the following futures []
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-0_0] [D] [s3transfer.tasks] ImmediatelyWriteIOGetObjectTask(transfer_id=0, {'bucket': 'toil-datasets', 'key': 'images/toil-logo-draft.png', 'extra_args': {}}) done waiting for dependent futures
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-0_0] [D] [s3transfer.tasks] Executing task ImmediatelyWriteIOGetObjectTask(transfer_id=0, {'bucket': 'toil-datasets', 'key': 'images/toil-logo-draft.png', 'extra_args': {}}) with kwargs {'client': <botocore.client.S3 object at 0x7f91e7ae28b0>, 'bucket': 'toil-datasets', 'key': 'images/toil-logo-draft.png', 'fileobj': <_io.BufferedWriter name='/public/groups/cgl/graph-genomes/anovak/build/amazon-genomics-cli/examples/demo-cwl-project/workflows/s3demo/tree/files/no-job/file-44e6c09ab9554dba960dd1695f03468e/stream'>, 'extra_args': {}, 'callbacks': [], 'max_attempts': 5, 'download_output_manager': <s3transfer.download.DownloadSeekableOutputManager object at 0x7f91f7df93a0>, 'io_chunksize': 262144, 'bandwidth_limiter': None}
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-1_0] [D] [s3transfer.utils] Releasing acquire 0/None
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-0_0] [D] [s3transfer.tasks] IOWriteTask(transfer_id=0, {'offset': 0}) about to wait for the following futures []
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-0_0] [D] [s3transfer.tasks] IOWriteTask(transfer_id=0, {'offset': 0}) done waiting for dependent futures
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-0_0] [D] [s3transfer.tasks] Executing task IOWriteTask(transfer_id=0, {'offset': 0}) with kwargs {'fileobj': <_io.BufferedWriter name='/public/groups/cgl/graph-genomes/anovak/build/amazon-genomics-cli/examples/demo-cwl-project/workflows/s3demo/tree/files/no-job/file-44e6c09ab9554dba960dd1695f03468e/stream'>, 'offset': 0}
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-0_0] [D] [s3transfer.tasks] CompleteDownloadNOOPTask(transfer_id=0, {}) about to wait for the following futures []
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-0_0] [D] [s3transfer.tasks] CompleteDownloadNOOPTask(transfer_id=0, {}) done waiting for dependent futures
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-0_0] [D] [s3transfer.tasks] Executing task CompleteDownloadNOOPTask(transfer_id=0, {}) with kwargs {}
[2022-05-11T14:45:21-0700] [ThreadPoolExecutor-0_0] [D] [s3transfer.utils] Releasing acquire 0/None
[2022-05-11T14:45:21-0700] [MainThread] [D] [toil.cwl.cwltoil] Sending file at: toilfile:117027:0:files/no-job/file-44e6c09ab9554dba960dd1695f03468e/stream
[2022-05-11T14:45:21-0700] [MainThread] [I] [toil.common] Successfully deleted the job store: FileJobStore(/public/groups/cgl/graph-genomes/anovak/build/amazon-genomics-cli/examples/demo-cwl-project/workflows/s3demo/tree)
Traceback (most recent call last):
  File "/public/home/anovak/build/toil/venv/bin/toil-cwl-runner", line 33, in <module>
    sys.exit(load_entry_point('toil', 'console_scripts', 'toil-cwl-runner')())
  File "/public/home/anovak/build/toil/src/toil/cwl/cwltoil.py", line 3447, in main
    import_files(
  File "/public/home/anovak/build/toil/src/toil/cwl/cwltoil.py", line 1527, in import_files
    visit_cwl_class_and_reduce(
  File "/public/home/anovak/build/toil/src/toil/cwl/utils.py", line 123, in visit_cwl_class_and_reduce
    for result in visit_cwl_class_and_reduce(rec[key], classes, op_down, op_up):
  File "/public/home/anovak/build/toil/src/toil/cwl/utils.py", line 120, in visit_cwl_class_and_reduce
    down_result = op_down(rec)
  File "/public/home/anovak/build/toil/src/toil/cwl/cwltoil.py", line 1454, in visit_file_or_directory_down
    get_listing(fs_access, rec, recursive=False)
  File "/public/home/anovak/build/toil/venv/lib/python3.9/site-packages/cwltool/utils.py", line 317, in get_listing
    for ld in fs_access.listdir(loc):
  File "/public/home/anovak/build/toil/venv/lib/python3.9/site-packages/cwltool/stdfsaccess.py", line 57, in listdir
    for entry in os.listdir(self._abs(fn))
FileNotFoundError: [Errno 2] No such file or directory: '/public/groups/cgl/graph-genomes/anovak/build/amazon-genomics-cli/examples/demo-cwl-project/workflows/s3demo/s3://toil-datasets/images'
```

I think we're using `cwltool`'s default FsAccess and not the Toil one that knows how to talk to S3, when we go to list the directory contents.

**Comment by boyangzhao** [comment]
This is the same exact error I observed. The path it was searching was the local path added in as prefix onto the s3:// path. Is there a solution for `Directory` type or this won't be supported still, even after this fix on `File`?

**Comment by adamnovak** [comment]
We will be able to support `Directory` objects from S3 when this is fixed. I've started on an implementation that will just use our `JobStore` implementations to fulfill URL types that they know about.

**Comment by adamnovak** [comment]
@boyangzhao I've merged a PR that fixes this for both `File` and `Directory` CWL types. If you use Toil from Git, it should work.

**Comment by boyangzhao** [comment]
Thanks Adam! Are the updated fixes in master branch? I've tried to checkout master, issues/4109-4094-4107-megabranch, or issues/4094-fix-s3-cwl branch, and either tried to pip install locally or make my own docker, I am still getting the same error that it didn't recognize the s3 file. I've also tried to use the latest docker from ucsc_cgl/toil. Is the fix on some other branch?

**Comment by boyangzhao** [comment]
@adamnovak following up on https://github.com/DataBiosphere/toil/issues/4091#issuecomment-1144714219, the error looks like being triggered here,

https://github.com/DataBiosphere/toil/blob/ec83920e1636fd24814688bf1569feebfae73620/src/toil/cwl/cwltoil.py#L3575

Error (I created a `zz_test/test.py` for debugging)

```
Exception has occurred: WorkflowException
 Reading s3://toil-datasets/wdl_templates.zip
 [Errno 2] No such file or directory: '/tmp/s3://toil-datasets/wdl_templates.zip'

During handling of the above exception, another exception occurred:


The above exception was the direct cause of the following exception:

  File "/tmp/toil/src/toil/cwl/cwltoil.py", line 3575, in main
    builder = tool._init_job(initialized_job_order, runtime_context)
  File "/tmp/toil/zz_test/test.py", line 5, in <module>
    main(args)
```

It looks like the code still doesn't recognize the s3, and added the `basedir` to the s3 directory, but maybe this is because of the cwltool is failing to recognize it? I've tried this on the master branch, and also the `AGC megabranch (#4113)` branch.

**Comment by adamnovak** [comment]
In #4113, I fixed taking CWL `Directory` objects from S3 as inputs to workflows. I added a test that runs this workflow: https://github.com/DataBiosphere/toil/blob/ec83920e1636fd24814688bf1569feebfae73620/src/toil/test/cwl/download_directory.cwl

With this input: https://github.com/DataBiosphere/toil/blob/ec83920e1636fd24814688bf1569feebfae73620/src/toil/test/cwl/download_directory_s3.json

And the merge commit passed on CI in [this job](https://ucsc-ci.com/databiosphere/toil/-/jobs/16236):
```
src/toil/test/cwl/cwlTest.py::CWLWorkflowTest::test_download_directory_s3 
-------------------------------- live log call ---------------------------------
INFO     cwltool:load_tool.py:102 Resolved '/builds/databiosphere/toil/src/toil/test/cwl/download_directory.cwl' to 'file:///builds/databiosphere/toil/src/toil/test/cwl/download_directory.cwl'
INFO     toil.job:job.py:2196 Saving graph of 2 jobs, 2 new
INFO     toil.job:job.py:2208 Processing job 'ResolveIndirect' kind-ResolveIndirect/instance-2b30x7c5 v0
INFO     toil.job:job.py:2208 Processing job 'CWLWorkflow' kind-CWLWorkflow/instance-gwct5ob4 v0
INFO     toil:__init__.py:442 Running Toil version 5.7.0a1-30b62dcef3de62c913f83b826171fa4817db0bff on host runner-s6qtqhdy-project-3-concurrent-9stbx2.
INFO     toil.leader:leader.py:983 0 jobs are running, 0 jobs are issued and waiting to run
INFO     toil.leader:leader.py:897 Issued job 'CWLJob' download_directory.cwl.file_from_directory.file_from_directory.cwl kind-CWLJob/instance-3ek83icx v1 with job batch system ID: 1 and cores: 1, disk: 3.0 Gi, and memory: 2.0 Gi
INFO     toil.leader:leader.py:297 Finished toil run successfully.
INFO     toil.common:common.py:910 Successfully deleted the job store: FileJobStore(/tmp/tmpnbokt9sx)
PASSED                                                                   [ 14%]
```

The code for this is currently in the `master` branch.

However, that code doesn't test exactly what you are doing in https://github.com/DataBiosphere/toil/issues/4091#issuecomment-1144714219, where you pass an S3 `File` straight to a top-level CommandLineTool, without an enclosing Workflow. I'll see if I can replicate that problem.
